{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-lab.fullname" . }}
  labels:
    app: {{ default .Values.secret.name | quote }}
    name: {{ default .Values.secret.name | quote }}
    app.kubernetes.io/name: {{ default .Values.api.name | quote }}
    {{ include "kube-lab.labels" . | nindent 4 }}
type: Opaque
stringData:
  DUMMY_TOKEN: {{ .Values.secret.DUMMY_TOKEN | quote }}
{{- end }}