apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-lab.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.api.service.name | quote }}
    app.kubernetes.io/component: {{ .Values.api.service.component | quote }}
    {{ include "kube-lab.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.api.name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
